apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::730950150977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QEBUHWX44KIP
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::730950150977:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-12T17:52:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1636"
  uid: 0ce86cda-6688-429c-af9c-5bbceb2b79f7
