apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::730950150977:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-980M0VK3RT89
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::730950150977:role/UdacityFlaskDeployCBKubectlRole
      username: anejas-uda
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-15T20:02:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5059"
  uid: ca48f217-b224-4a22-bd21-934504a3dded
